---
title: "Xaringan Tool"
---

::: {style="text-align: justify;"}
This week, we were tasked with creating a presentation using <strong>Xaringan</strong>, an R package for building dynamic and reproducible slides with <strong>R Markdown</strong>. The assignment followed the usual structure of <strong>summary</strong>, <strong>applications</strong>, and <strong>reflections</strong>, but with a twist: presenting it through Xaringan.

For the content, I initially considered well-known satellites like Landsat and Sentinel, but I chose to explore a less familiar sensor to expand my knowledge. I selected the <strong>Total Ozone Mapping Spectrometer (TOMS)</strong>, a groundbreaking sensor that transformed our understanding of the ozone layer and atmospheric composition. The presentation highlights its <strong>design</strong>, <strong>purpose</strong>, and <strong>applications</strong>, and concludes with reflections on what I learned about TOMS, its applications, and its potential for future use in addressing global environmental challenges.
:::

## Presentation

```{r echo= FALSE}
xaringanExtra::embed_xaringan(url = "https://nourahalhosain.github.io/RS_Xaringan/",  ratio = "4:3")
```

## Reflections on Xaringan
::: {style="text-align: justify;"}
Since taking CASA005 last term, I have been curious about how course materials are created. I often find myself sharing presentations via email, only to have to resend them after updates, which made me eager to try Xaringan! Initially, I felt a bit disappointed to learn that it is an R-based package, as I’m not the biggest fan of R and don’t find it particularly intuitive—mostly because I've used it primarily for statistical analysis in the past. However, I feel more comfortable with R now, having used it in various courses.

When I started building my slides, the process was challenging. I attempted to follow the suggested Markdown structure, but it felt restrictive compared to the general HTML I was accustomed to. As a result, I found myself using HTML components for elements that were difficult to manage in Markdown. I’m unsure if this is considered bad practice or acceptable as long as it works!
:::